name: Ethereum Typescript
on:
  push:
    paths:
      - 'ethereum/gateway-eth-ts/**'
      - '.github/**'
  pull_request:
jobs:
  ethereum-build:
    name: Build, lint and test the ethereum libraries on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./ethereum/gateway-eth-ts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: yarn-ethereum-${{ hashFiles('ethereum/gateway-eth-ts/yarn.lock') }}

      - name: NPM login
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install
        run: yarn

      - name: Lint
        run: yarn workspaces run lint

      - name: Build
        run: yarn workspaces run build

      - name: Run tests
        run: yarn test
